services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: foodmarketplace-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - food-net  # <-- backend must be on the same network
    dns:
      - 8.8.8.8

  redis:
    image: redis:latest
    container_name: redis-food-app
    ports:
      - "6379:6379"
    networks:
      - food-net

networks:
  food-net:
    driver: bridge
