FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

# Force IPv4 DNS resolution for Neon DB
# ENV NODE_OPTIONS=--dns-result-order=ipv4first

CMD ["npm", "run", "dev"]